#cloud-config
bootcmd:
# There is a key issue in the current Alma Linux images, https://github.com/Azure/cyclecloud-slurm/issues/214
- rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux

#mounts:

#packages:


#write_files:

#runcmd:
