#cloud-config
bootcmd:
# There is a key issue in the current Alma Linux images, https://github.com/Azure/cyclecloud-slurm/issues/214
- rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux

#mounts:

#packages:


#write_files:

runcmd:
-  mkdir /slurm
-  cd /slurm
-  mkdir ./experiment01
-  cd ./experiment01
-  touch cloudinit_was_here.txt
-  chmod 666 cloudinit_was_here.txt 
-  wget https://github.com/gevaertw/CycleCloudDemo/blob/main/README.md 
-  wget https://github.com/gevaertw/CycleCloudDemo/tree/main/slurm/slurmtest01.sh
-  wget https://github.com/gevaertw/CycleCloudDemo/tree/main/slurm/slurmtest02.sh
-  wget https://github.com/gevaertw/CycleCloudDemo/tree/main/slurm/hpcjob01.sh
-  chmod +x slurmtest01.sh
-  chmod +x slurmtest02.sh
-  chmod +x hpcjob01.sh
