#cloud-config
timezone: Europe/Brussels

# hpc htc node configuration for the CycleCloud Slurm Cluster

# There is a key issue in the current Alma Linux images, https://github.com/Azure/cyclecloud-slurm/issues/214
# seems resolved now commented out for deletion later on..
#bootcmd:
#- rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
# bootcmd:
# the following line disables hyper-threading, some HPC workloads may benefit from this
# - for cpunum in $(cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | cut -s -d- -f2- | tr ',' '\n' | sort -un); do echo 0 > /sys/devices/system/cpu/cpu$cpunum/online; done


#mounts:

packages:
- python39
- jq
- tmux
- at

#write_files:

runcmd:
# start some services
- systemctl start atd
# Install the azNFS package
- export AZNFS_NONINTERACTIVE_INSTALL=1
- wget -O - -q https://github.com/Azure/AZNFS-mount/releases/latest/download/aznfs_install.sh | bash
# Mount the cyclenfs NFS share that sits on the storage accounts, make sure to replace the storage account name with the actual one.
- mkdir -p /cyclenfs
- chmod -R 755 /cyclenfs
- mount -t aznfs -o sec=sys,vers=3,nolock,proto=tcp nfscyclesa8168kt436884.blob.core.windows.net:/nfscyclesa8168kt436884/cyclenfs  /cyclenfs
# Configure & run Moneo monitor
- /cyclenfs/CycleCloudDemo/Installers/Moneo/moneoInstallLinux.sh
