#cloud-config
timezone: Europe/Brussels

# scheduler node configuration for the CycleCloud Slurm Cluster

#mounts:

packages:
- python39
- jq
- tmux
- at
- mysql
- nano

#write_files:

runcmd:
# start some services
- systemctl start atd
# Install the azNFS package
- export AZNFS_NONINTERACTIVE_INSTALL=1
- wget -O - -q https://github.com/Azure/AZNFS-mount/releases/latest/download/aznfs_install.sh | bash
# Mount the cyclenfs NFS share that sits on the storage accounts, make sure to replace the storage account name with the actual one.
- mkdir -p /cyclenfs
- chmod -R 755 /cyclenfs
- mount -t aznfs -o sec=sys,vers=3,nolock,proto=tcp nfscyclesa8168kt436884.blob.core.windows.net:/nfscyclesa8168kt436884/cyclenfs  /cyclenfs
# Configure & run Moneo monitor (keep this line last)
- /cyclenfs/CycleCloudDemo/Installers/Moneo/moneoInstallLinux.sh
