#cloud-config
timezone: Europe/Brussels

# Login node configuration for the CycleCloud Slurm Cluster

# password for these users: "DevDesk_45" choose something else :)  The passwd below is encrypted.
users:
- name: desktop01
  passwd: "$6$mapydqZujtX3R.eu$qcPZHXukedd4QtsunU3vByg6UFXZsJMm4NwPrYxYbgSBNA3IWRpSke5d9ek2S984niyfcmEJH.zJnTVzTVHU5."
  shell: /bin/bash
  lock-passwd: false
  ssh_pwauth: True
  chpasswd: { expire: False }
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: users, admin

# There is a key issue in the current Alma Linux images, https://github.com/Azure/cyclecloud-slurm/issues/214
# seems resolved now commented out for deletion later on..
#bootcmd:
#- rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux

#mounts:

packages:
- python39
- jq
- tmux
- at
- nano

#write_files:

runcmd:
# start some services
- systemctl start atd
# Install the azNFS package
- export AZNFS_NONINTERACTIVE_INSTALL=1
- wget -O - -q https://github.com/Azure/AZNFS-mount/releases/latest/download/aznfs_install.sh | bash
# Mount the cyclenfs NFS share that sits on the storage accounts, make sure to replace the storage account name with the actual one.
- mkdir -p /cyclenfs
- chmod -R 755 /cyclenfs
- mount -t aznfs -o sec=sys,vers=3,nolock,proto=tcp nfscyclesa8168kt436884.blob.core.windows.net:/nfscyclesa8168kt436884/cyclenfs  /cyclenfs
# Add GUI
- /cyclenfs/CycleCloudDemo/Installers/Alma/guiInstallAlma.sh
# Configure & run Moneo monitor (keep this line last)
- /cyclenfs/CycleCloudDemo/Installers/Moneo/moneoInstallLinux.sh


